logging:
  level:
    root: info
  config: classpath:logback-config.xml
  file:
    path: /tmp/logs
spring:
  application:
    name: rabbitmq
  rabbitmq:
#    host: 192.168.1.161
#    port: 15672
#    username: xyq
#    password: xyq123456!
    listener:
      simple:
        batch-size: 10
        consumer-batch-enabled: true
server:
  port: 8002